-- Allergen catalog. INSERT IGNORE keeps re-runs idempotent (code is unique).
-- Animal-derived groups (milk, egg, seafood) are omitted: the platform is fully vegan (BR-06).
INSERT IGNORE INTO allergens (code, name, category) VALUES
('GLUTEN', 'Gluten (lúa mì, lúa mạch)', 'GRAIN'),
('BUCKWHEAT', 'Kiều mạch', 'GRAIN'),
('CORN', 'Bắp (ngô)', 'GRAIN'),
('PEANUT', 'Đậu phộng', 'LEGUME'),
('SOY', 'Đậu nành', 'LEGUME'),
('MUNG_BEAN', 'Đậu xanh', 'LEGUME'),
('CASHEW', 'Hạt điều', 'NUT_SEED'),
('TREE_NUT', 'Hạt cây khác (hạnh nhân, óc chó, mắc ca)', 'NUT_SEED'),
('SESAME', 'Mè (vừng)', 'NUT_SEED'),
('COCONUT', 'Dừa', 'NUT_SEED'),
('TOMATO', 'Cà chua', 'VEGETABLE'),
('EGGPLANT', 'Cà tím', 'VEGETABLE'),
('TARO', 'Khoai môn', 'VEGETABLE'),
('CASSAVA', 'Khoai mì (sắn)', 'VEGETABLE'),
('BAMBOO_SHOOT', 'Măng', 'VEGETABLE'),
('CELERY', 'Cần tây', 'VEGETABLE'),
('CORIANDER', 'Rau mùi (ngò)', 'VEGETABLE'),
('GARLIC', 'Tỏi', 'VEGETABLE'),
('ONION', 'Hành', 'VEGETABLE'),
('MANGO', 'Xoài', 'FRUIT'),
('PINEAPPLE', 'Dứa (thơm)', 'FRUIT'),
('PAPAYA', 'Đu đủ', 'FRUIT'),
('AVOCADO', 'Bơ', 'FRUIT'),
('DURIAN', 'Sầu riêng', 'FRUIT'),
('JACKFRUIT', 'Mít', 'FRUIT'),
('LYCHEE', 'Vải', 'FRUIT'),
('STRAWBERRY', 'Dâu tây', 'FRUIT'),
('MUSHROOM', 'Nấm (các loại)', 'MUSHROOM'),
('CHILI', 'Ớt', 'SPICE'),
('MUSTARD', 'Mù tạt', 'SPICE'),
('SULPHITE', 'Sulfite', 'ADDITIVE'),
('MSG', 'Bột ngọt (MSG)', 'ADDITIVE');

-- 18 Seed Vegan Recipes
INSERT IGNORE INTO recipes (id, name, meal_type, ingredients, calories, protein, carbs, fat, instructions, vegan, allergen_codes, created_at) VALUES
(1, 'Phở Chay Nấm Đậu Hũ', 'BREAKFAST', 'Bánh phở, nấm đùi gà, nấm hương, đậu phụ chiên, quế, hồi, hành ngò', 380.0, 14.5, 62.0, 8.0, 'Nấu nước dùng rau củ với hồi quế thảo quả nướng thơm trong 45 phút. Trụng bánh phở, xếp nấm xào và đậu phụ lên trên rồi chan nước dùng nóng hổi.', 1, 'SOY,GLUTEN', NOW()),
(2, 'Bún Riêu Chay Cà Chua', 'BREAKFAST', 'Bún tươi, đậu phụ non xay, cà chua, me, nấm rơm, rau sống ghém', 350.0, 13.0, 55.0, 9.0, 'Xào cà chua tạo màu đỏ tự nhiên. Trộn đậu hũ non nêm chút hạt nêm chay làm riêu. Nấu nước lèo chua thanh với me rồi múc vào bát bún.', 1, 'SOY,TOMATO', NOW()),
(3, 'Bánh Mì Pa-tê Nấm Đậu Lăng', 'BREAKFAST', 'Bánh mì giòn, nấm mỡ, đậu lăng nâu, dưa leo, ngò gai, ớt', 320.0, 10.5, 48.0, 9.5, 'Xay nhuyễn đậu lăng hấp chín với nấm xào thơm hành boa-rô làm pate. Quết pate nấm vào bánh mì nóng giòn ăn kèm dưa góp.', 1, 'GLUTEN,MUSHROOM', NOW()),
(4, 'Cháo Yến Mạch Hạt Sen Tươi', 'BREAKFAST', 'Yến mạch cán dẹt, hạt sen Huế, nấm hương tươi, cà rốt, tiêu xanh', 290.0, 9.0, 52.0, 5.0, 'Hầm mềm hạt sen tươi với nước dùng rau củ. Thêm yến mạch và nấm hương băm nhỏ, khuấy đều nấu 10 phút cho sánh mịn rồi rắc tiêu ngò.', 1, '', NOW()),
(5, 'Sinh Tố Bơ Chuối Hạt Hạnh Nhân', 'BREAKFAST', 'Bơ sáp chín, chuối tiêu chín đông đá, sữa đậu nành hoặc yến mạch, hạnh nhân băm', 310.0, 7.5, 42.0, 14.0, 'Cho bơ, chuối, sữa chua hạt và sữa hạt vào máy xay sinh tố xay mịn màng. Đổ ra ly và rắc hạnh nhân nướng thơm giòn.', 1, 'TREE_NUT,AVOCADO,SOY', NOW()),
(6, 'Cơm Gạo Lứt Đậu Hũ Xào Nấm', 'LUNCH', 'Gạo lứt đỏ, đậu hũ chiên vàng, nấm đùi gà, ớt chuông, súp lơ xanh', 450.0, 18.0, 68.0, 11.0, 'Nấu cơm gạo lứt dẻo thơm. Xào đậu hũ cắt con chì cùng nấm và rau củ với nước tương tamari hảo hạng và dầu hào nấm chay.', 1, 'SOY,MUSHROOM', NOW()),
(7, 'Canh Chua Chay Đậu Hũ Dọc Mùng', 'LUNCH', 'Đậu hũ trắng non, dọc mùng tước vỏ, đậu bắp, dứa thơm, cà chua, ngò om me chua', 220.0, 11.0, 28.0, 6.5, 'Phi thơm boa-rô, cho cà chua và dứa xào sơ. Đổ nước me đun sôi, thả đậu bắp dọc mùng và đậu hũ non, nêm nếm chua thanh đậm vị.', 1, 'SOY,TOMATO,PINEAPPLE', NOW()),
(8, 'Đậu Phụ Sốt Cà Chua Nấm Đông Cô', 'LUNCH', 'Đậu hũ mơ chiên giòn, nấm đông cô khô ngâm nở, cà chua chín mọng, hành hoa ngò rí', 280.0, 16.0, 22.0, 14.0, 'Đậu hũ cắt miếng rán giòn vỏ mềm trong. Sốt cà chua thật nhuyễn sánh, thả nấm đông cô thái sợi và đậu vào om nhỏ lửa 10 phút ngấm sốt.', 1, 'SOY,TOMATO,MUSHROOM', NOW()),
(9, 'Cà Ri Chay Khoai Lang Đậu Gà', 'LUNCH', 'Đậu gà ngâm mềm, khoai lang vàng, cà rốt, nước cốt dừa, bột cà ri Ấn Độ', 420.0, 15.5, 58.0, 14.5, 'Nấu nhừ đậu gà. Phi thơm bột cà ri và sả đập dập, cho khoai lang cà rốt vào xào rồi đun sôi cùng nước cốt dừa sánh béo ngậy.', 1, 'COCONUT', NOW()),
(10, 'Gỏi Cuốn Chay Sốt Đậu Phộng', 'LUNCH', 'Bánh tráng gạo lứt, bún tươi, đậu hũ chiên thái sợi, nấm xào, rau thơm các loại, bơ đậu phộng', 260.0, 10.0, 38.0, 7.5, 'Nhúng bánh tráng xếp rau sống xà lách tươi, đậu hũ nấm sợi rồi cuốn chặt tay. Chấm với sốt tương đen pha bơ đậu phộng béo bùi.', 1, 'PEANUT,SOY', NOW()),
(11, 'Nấm Rơm Kho Tiêu Nước Dừa Tươi', 'DINNER', 'Nấm rơm búp tươi sạch, nước dừa xiêm, tiêu đen đập dập, ớt hiểm, nước tương hảo hạng', 250.0, 8.5, 20.0, 15.0, 'Ướp nấm rơm với nước tương, đường mía, tiêu và chút dầu mè. Cho vào nồi đất nấu nhỏ lửa với nước dừa tươi đến khi nước kho sánh keo lại.', 1, 'MUSHROOM,COCONUT,SOY', NOW()),
(12, 'Súp Bí Đỏ Hạt Điều Kem Béo', 'DINNER', 'Bí đỏ hồ lô ngọt, hạt điều tươi ngâm mềm, cần tây, hành boa-rô, bánh mì sấy giòn', 310.0, 7.0, 36.0, 16.0, 'Hấp chín bí đỏ cùng hạt điều tươi. Cho vào máy xay thật nhuyễn mịn cùng nước dùng rau củ, đun sôi lăn tăn nêm muối biển và tiêu thơm.', 1, 'CASHEW,CELERY', NOW()),
(13, 'Mì Ý Sốt Cà Chua Đậu Lăng Đỏ', 'DINNER', 'Mì Ý nguyên cám Spaghetti, đậu lăng đỏ, cà chua xay nhuyễn, lá húng quế oregano', 430.0, 17.0, 72.0, 8.0, 'Luộc mì Ý chuẩn al dente. Nấu sốt Bolognese chay từ đậu lăng đỏ và cà chua nêm thảo mộc Ý thơm lừng, rưới đều lên mì thưởng thức nóng.', 1, 'GLUTEN,TOMATO', NOW()),
(14, 'Rau Củ Xào Ngũ Sắc Ngon Giòn', 'DINNER', 'Bông cải xanh, cà rốt tỉa hoa, ngô bao tử, ớt chuông đỏ vàng, nấm hương', 190.0, 6.0, 24.0, 7.5, 'Chần sơ rau củ qua nước sôi pha chút muối. Phi thơm tỏi boa-rô, xào nhanh trên lửa lớn để rau giữ trọn màu sắc tươi và độ giòn ngọt tự nhiên.', 1, 'MUSHROOM', NOW()),
(15, 'Canh Rong Biển Đậu Hũ Non Bí Đao', 'DINNER', 'Rong biển Wakame Hàn Quốc, bí đao xanh mát, đậu hũ non mềm, nấm kim châm', 160.0, 10.0, 16.0, 5.5, 'Nấu sôi nước dùng rau củ, thả bí đao thái mỏng nấu chín tới. Cho tiếp rong biển và nấm kim châm, cuối cùng thả nhẹ đậu hũ non nêm vị thanh ngọt.', 1, 'SOY', NOW()),
(16, 'Chè Đậu Xanh Hạt Sen Cốt Dừa', 'SNACK', 'Đậu xanh đãi vỏ, hạt sen khô ninh mềm, nước cốt dừa nguyên chất, đường phèn thanh', 220.0, 6.5, 40.0, 4.5, 'Ninh mềm đậu xanh và hạt sen với đường phèn. Múc ra chén, chan chút nước cốt dừa tươi thơm béo ngậy thưởng thức mát lành.', 1, 'MUNG_BEAN,COCONUT', NOW()),
(17, 'Salad Quả Bơ Hạt Óc Chó Chanh Leo', 'SNACK', 'Bơ sáp béo ngậy thái hạt lựu, quả óc chó nướng giòn, rau rocket, sốt chanh leo chua ngọt', 240.0, 5.0, 18.0, 17.0, 'Trộn đều rau xà lách sạch cùng bơ sáp và cà chua bi. Rưới nước sốt chanh leo thanh mát và rắc vụn hạt óc chó nướng vàng rụm lên trên.', 1, 'TREE_NUT,AVOCADO', NOW()),
(18, 'Sữa Hạt Mắc Ca Yến Mạch Tự Nhiên', 'SNACK', 'Hạt mắc ca tươi bóc vỏ, yến mạch cán dẹt, chà là tự nhiên tạo ngọt thanh', 180.0, 4.5, 22.0, 8.5, 'Nấu và xay mịn hạt mắc ca cùng yến mạch và quả chà là. Lọc qua rây mịn lấy sữa hạt thơm ngậy bổ dưỡng, dùng nóng hoặc lạnh đều tuyệt vời.', 1, 'TREE_NUT', NOW());

-- 6 Seed Vegan Restaurants
INSERT IGNORE INTO restaurants (id, name, address, latitude, longitude, description, type, supported_dishes, created_at) VALUES
(1, 'Nhà Hàng Chay Ưu Đàm (U Dam Chay)', '34 Hàng Bài, Hoàn Kiếm, Hà Nội', 21.023300, 105.852500, 'Không gian ẩm thực Phật giáo thanh tịnh, thiết kế kiến trúc ba tầng độc đáo, các món chay kết hợp tinh tế giữa nguyên liệu truyền thống và hiện đại.', 'Nhà hàng chay cao cấp', 'Phở chay nấm đùi gà, Lẩu nấm cung đình Ưu Đàm, Cơm lá sen hạt điều, Nem nấm chiên xù', NOW()),
(2, 'Nhà Hàng Chay Sadhu', '87 Lý Thường Kiệt, Cửa Nam, Hoàn Kiếm, Hà Nội', 21.024800, 105.845600, 'Mô hình buffet chay gọi món cao cấp tại bàn với thực đơn hơn 60 món ăn mỹ vị, mang lại cảm giác bình an và trọn vẹn vị giác.', 'Buffet chay cao cấp', 'Súp bí đỏ kem nấm, Bánh đúc nóng Sadhu, Cơm rang nấm truffle, Chè hạt sen nhãn nhục', NOW()),
(3, 'Quán Cơm Chay Nàng Sen', '120 Yên Lãng, Đống Đa, Hà Nội', 21.011800, 105.815200, 'Quán chay ấm cúng bình dân phục vụ cơm suất và các món chay dinh dưỡng cho dân văn phòng và gia đình hàng ngày.', 'Quán chay bình dân', 'Cơm suất thập cẩm nấm kho, Đậu hũ sốt cà chua, Canh chua bông so đũa, Giò nấm chay luộc', NOW()),
(4, 'Hum Vegetarian - Lounge & Restaurant', '2 Thi Sách, Bến Nghé, Quận 1, TP. Hồ Chí Minh', 10.777900, 106.705100, 'Nhà hàng chay nổi tiếng bậc nhất Sài Gòn với phong cách ẩm thực thanh lịch, nguyên liệu rau củ hữu cơ tươi ngon theo mùa.', 'Nhà hàng chay cao cấp', 'Gỏi cuốn nấm nướng sốt tương đậu, Cà ri xanh rau củ nước cốt dừa, Cơm chiên trái dứa, Canh nấm sả ớt', NOW()),
(5, 'Pi Vegetarian Bistro', '19 Võ Văn Tần, Phường 6, Quận 3, TP. Hồ Chí Minh', 10.776100, 106.691700, 'Phong cách mộc mạc ấm áp như căn bếp gia đình, món chay đậm đà bản sắc Đông Nam Á, được giới trẻ và du khách quốc tế rất ưa chuộng.', 'Quán chay hiện đại', 'Cơm gạo lứt xào nấm đậu hũ, Salad bơ sốt chanh leo, Đậu hũ chiên sả ớt, Súp bí đỏ hạt điều', NOW()),
(6, 'Quán Chay Tâm An', '48 Lê Duẩn, Hải Châu, Đà Nẵng', 16.069700, 108.219500, 'Địa chỉ ẩm thực thuần chay quen thuộc tại trung tâm Đà Nẵng, giá cả hợp lý, món ăn phong phú đậm hương vị miền Trung.', 'Quán chay truyền thống', 'Mì Quảng chay nấm đậu, Bún riêu chay miền Trung, Bánh xèo chay giòn rụm, Canh rong biển đậu non', NOW());
